export const metadata = {
  title: 'Gerenciador de produtos',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" href="../../public/favicon.png" />
      <body>{children}</body>
    </html>
  )
}
